---
title: "group7"
output: html_document
---

```{r setup}
pacman::p_load(tidyverse,ggplot2,haven,quantreg,extremefit,lmtest,sandwich)
library(quantreg)
#install.packages("extremefit")
library(extremefit)
library(estimatr,stats)

```

```{r prep}
dataframe_paths <- list.files( path ="../Autor-Dorn-Hanson-ChinaSyndrome-FileArchive/dta", full.names=T)
dataframe_list <- lapply(dataframe_paths, read_dta)
```

# Appendix Table 1

## Panel A

```{r 1a}

Table1_data <- dataframe_list[[5]]
view(Table1_data)

Table1_data_90 <- Table1_data|>filter(yr==1990)
Table1_data_00 <- Table1_data|>filter(yr==2000)

quantile(Table1_data_90$d_tradeusch_pw, c(0.1, 0.25, 0.5, 0.75, 0.9))
quantile(Table1_data_00$d_tradeusch_pw, c(0.1, 0.25, 0.5, 0.75, 0.9))

probs <- c(0.1, 0.25, 0.5, 0.75, 0.9)

# 90年のpercentile
weights_90 <- Table1_data_90$timepwt48
Table1_percentile_90 <- wquantile(Table1_data_90$d_tradeusch_pw, probs, weights_90)

# 2000年のpercentile
weights_00 <- Table1_data_00$timepwt48
Table1_percentile_00 <- wquantile(Table1_data_00$d_tradeusch_pw, probs, weights_00)
paste(Table1_percentile_00)
```

## Panel B

```{r 1b}
# 90年の上位40CZ
  Table1_data_90_B <- Table1_data_90 |>
    arrange(-l_popcount) |>
    slice(seq(1:40))|>
    arrange(-d_tradeusch_pw)

#
Panel_B_90  <- Table1_data_90_B |>select(city,d_tradeusch_pw)|>slice(c(seq(1,10),20,21,seq(31,40)))  


# 2000年の上位40CZ
city_key <- Table1_data_90_B|>
  select(city)

Table1_data_00_B <- Table1_data_00 |>
  select(city, d_tradeusch_pw) |>
  filter(city %in% city_key$city) |>
  arrange(-d_tradeusch_pw)

#
Panel_B_00  <- Table1_data_00_B |>slice(c(seq(1,10),20,21,seq(31,40))) 

#for(i in c(seq(1,10),20,21,seq(31,40))){
#  print(paste(i),Table1_data_90_B$city[i],Table1_data_90_B$d_tradeusch_pw[i],Table1_data_00_#B$city[i],Table1_data_00_B$d_tradeusch_pw[i])
#}
paste(select(Table1_data_90_B,city,d_tradeusch_pw))
paste(Table1_data_00_B)

```

# Figure 2A

```{r 2a}
workfile_china_long <- read_dta("../Autor-Dorn-Hanson-ChinaSyndrome-FileArchive/dta/workfile_china_long.dta")

workfile_china_long <- workfile_china_long |>
  mutate(d_tradeusch_pw_sqrtw = sqrt(workfile_china_long$timepwt48) * workfile_china_long$d_tradeusch_pw)|>
  mutate(d_tradeotch_pw_lag_sqrtw = sqrt(workfile_china_long$timepwt48) * workfile_china_long$d_tradeotch_pw_lag)|>
  mutate(l_shind_manuf_cbp_sqrtw = sqrt(workfile_china_long$timepwt48)*workfile_china_long$l_shind_manuf_cbp)

#figure_2a_1 <- lm(d_tradeusch_pw_sqrtw ~ d_tradeotch_pw_lag_sqrtw + l_shind_manuf_cbp_sqrtw, data = workfile_china_long)
#coeftest(figure_2a_1, vcov = vcovHC(figure_2a_1, type = "HC1"))

#workfile_china_long <- workfile_china_long |> 
#  mutate(predicted_x = predict(figure_2a_1))

#ggplot(workfile_china_long, aes(x = predicted_x/sqrt(timepwt48), y = d_tradeusch_pw_sqrtw/sqrt(timepwt48))) +
#  geom_point()

figure_2a_1 <- lm_robust(d_tradeusch_pw ~ d_tradeotch_pw_lag + l_shind_manuf_cbp, data = workfile_china_long,weights=timepwt48,  clusters=statefip,　se_type="stata")

# TSLS 
# d_tradeusch_pwの中でd_tradeotch_pw_lagが説明できる部分を取り出す（残差）y axis
tsls_b_eq1 <- lm_robust(d_tradeusch_pw ~ l_shind_manuf_cbp, data = workfile_china_long,weights=timepwt48,  clusters=statefip,se_type="stata")
residual_eq1 <- workfile_china_long$d_tradeusch_pw - tsls_b_eq1$fitted.values

# d_tradeotch_pw_lagとl_shind ( x axis)
tsls_b_eq2 <- lm_robust(d_tradeotch_pw_lag ~ l_shind_manuf_cbp, data = workfile_china_long,　weights=timepwt48,  clusters=statefip,se_type="stata")
residual_eq2 <- workfile_china_long$d_tradeotch_pw_lag - tsls_b_eq2$fitted.values

df_residuals <- data.frame( residual_eq1, residual_eq2, workfile_china_long$timepwt48, workfile_china_long$statefip)
regress_line_fig2_A <-  lm_robust(data = df_residuals, residual_eq1 ~ residual_eq2, weights = workfile_china_long.timepwt48, se_type = "stata",  clusters=workfile_china_long.statefip)
summary(regress_line_fig2_A)

plot(df_residuals$residual_eq2, df_residuals$residual_eq1, xlab= "Change in predicted import exposure per wprker (in kUSD)", ylab= "Change in import exposure per worker (in kUSD)", main = "Panel A. 2SLS first stage regression, full sample", ylim = c(-10, 50), xlim = c(-10, 30), pch = 16)
grid()
abline(regress_line_fig2_A,col="gray", lwd = 3)
mtext("First stage regression, 1990-2007", side = 3, line =0.5, col ="black")

# plot 
#ggplot(aes(x= residual_eq2 , y= residual_eq1),  data = df_residuals) +
#  geom_point() +
#  geom_smooth(method = "lm", se= FALSE)
  


summary(figure_2a_1)
```

# Figure 2B

```{r 2b}
figure_2b_1 <- lm_robust(d_pct_manuf ~ d_tradeotch_pw_lag + l_shind_manuf_cbp, data = workfile_china_long,weights=timepwt48,  clusters=statefip,　se_type="stata")

# TSLS 

tsls_b_eq1 <- lm_robust(d_pct_manuf ~ l_shind_manuf_cbp, data = workfile_china_long,weights=timepwt48,  clusters=statefip,se_type="stata")
residual_b_eq1 <- workfile_china_long$d_pct_manuf - tsls_b_eq1$fitted.values

# d_tradeotch_pw_lagとl_shind ( x axis)
tsls_b_eq2 <- lm_robust(d_tradeotch_pw_lag ~ l_shind_manuf_cbp, data = workfile_china_long,　weights=timepwt48,  clusters=statefip,se_type="stata")
residual_b_eq2 <- workfile_china_long$d_tradeotch_pw_lag - tsls_b_eq2$fitted.values

# y axis 
df_residuals_B <- data.frame( residual_b_eq1, residual_b_eq2, workfile_china_long$timepwt48, workfile_china_long$statefip)
regress_line_fig2_B <-  lm_robust(data = df_residuals_B, residual_b_eq1 ~ residual_b_eq2, weights = workfile_china_long.timepwt48, se_type = "stata",  clusters=workfile_china_long.statefip)
summary(regress_line_fig2_B)

#plot
plot(df_residuals_B$residual_b_eq2, df_residuals_B$residual_b_eq1, xlab= "Change in predicted import exposure per wprker (in kUSD)", ylab= "Change % manufacturing emp inn working-age pop. (in kUSD)", main = "Panel B. OLS reduced form regression, full sample", ylim = c(-17, 12), xlim = c(-10, 30), pch = 16)
grid()
abline(regress_line_fig2_B,col="gray", lwd = 3)
mtext("Changein manufacturing emp by CZ, 1990-2007", side = 3, line =0.5, col ="black")
```

# Table 3

## I. 1990-2007 stacked first differences

```{r 3I}
workfile_china <- read_dta("../Autor-Dorn-Hanson-ChinaSyndrome-FileArchive/dta/workfile_china.dta")

table3_1_1 <- iv_robust(d_sh_empl_mfg ~ d_tradeusch_pw + t2 | d_tradeotch_pw_lag + t2, weights = timepwt48, clusters = statefip, data = workfile_china, se_type = "stata") 

table3_1_2 <- iv_robust(d_sh_empl_mfg ~ d_tradeusch_pw + l_shind_manuf_cbp + t2 | d_tradeotch_pw_lag + l_shind_manuf_cbp + t2, weights = timepwt48, clusters = statefip, data = workfile_china, se_type = "stata") 

table3_1_3 <- iv_robust(d_sh_empl_mfg ~ d_tradeusch_pw + l_shind_manuf_cbp + reg_midatl + reg_encen + reg_wncen + reg_satl + reg_escen + reg_wscen + reg_mount + reg_pacif + t2 | d_tradeotch_pw_lag + l_shind_manuf_cbp + reg_midatl+ reg_encen + reg_wncen + reg_satl + reg_escen + reg_wscen + reg_mount + reg_pacif + t2, weights = timepwt48, clusters = statefip, data = workfile_china, se_type = "stata") 

table3_1_4 <- iv_robust(d_sh_empl_mfg ~ d_tradeusch_pw + l_shind_manuf_cbp + l_sh_popedu_c + l_sh_popfborn + l_sh_empl_f +reg_midatl + reg_encen + reg_wncen + reg_satl + reg_escen + reg_wscen + reg_mount + reg_pacif + t2 | d_tradeotch_pw_lag + l_shind_manuf_cbp + l_sh_popedu_c + l_sh_popfborn + l_sh_empl_f + reg_midatl+ reg_encen + reg_wncen + reg_satl + reg_escen + reg_wscen + reg_mount + reg_pacif + t2, weights = timepwt48, clusters = statefip, data = workfile_china, se_type = "stata") 

table3_1_5 <- iv_robust(d_sh_empl_mfg ~ d_tradeusch_pw + l_shind_manuf_cbp + l_sh_routine33 + l_task_outsource + reg_midatl + reg_encen + reg_wncen + reg_satl + reg_escen + reg_wscen + reg_mount + reg_pacif + t2 | d_tradeotch_pw_lag + l_shind_manuf_cbp + l_sh_routine33 + l_task_outsource + reg_midatl+ reg_encen + reg_wncen + reg_satl + reg_escen + reg_wscen + reg_mount + reg_pacif + t2, weights = timepwt48, clusters = statefip, data = workfile_china, se_type = "stata") 

table3_1_6 <- iv_robust(d_sh_empl_mfg ~ d_tradeusch_pw + l_shind_manuf_cbp + l_sh_popedu_c + l_sh_popfborn + l_sh_empl_f + l_sh_routine33 + l_task_outsource + reg_midatl + reg_encen + reg_wncen + reg_satl + reg_escen + reg_wscen + reg_mount + reg_pacif + t2 | d_tradeotch_pw_lag + l_shind_manuf_cbp + l_sh_popedu_c + l_sh_popfborn + l_sh_empl_f + l_sh_routine33 + l_task_outsource + reg_midatl+ reg_encen + reg_wncen + reg_satl + reg_escen + reg_wscen + reg_mount + reg_pacif + t2, weights = timepwt48, clusters = statefip, data = workfile_china, se_type = "stata") 

summary(table3_1_1)
summary(table3_1_2)
summary(table3_1_3)
summary(table3_1_4)
summary(table3_1_5)
summary(table3_1_6)
```

## II. 2SLS first stage estimates

```{r 3II}
table3_2_1 <- lm_robust(d_tradeusch_pw ~ d_tradeotch_pw_lag + t2, weights = timepwt48, clusters = statefip, data = workfile_china, se_type = "stata") 

table3_2_2 <- lm_robust(d_tradeusch_pw ~ d_tradeotch_pw_lag + l_shind_manuf_cbp + t2, weights = timepwt48, clusters = statefip, data = workfile_china, se_type = "stata") 

table3_2_3 <- lm_robust(d_tradeusch_pw ~ d_tradeotch_pw_lag + l_shind_manuf_cbp + reg_midatl+ reg_encen + reg_wncen + reg_satl + reg_escen + reg_wscen + reg_mount + reg_pacif + t2, weights = timepwt48, clusters = statefip, data = workfile_china, se_type = "stata") 

table3_2_4 <- lm_robust(d_tradeusch_pw ~ d_tradeotch_pw_lag + l_shind_manuf_cbp + l_sh_popedu_c + l_sh_popfborn + l_sh_empl_f + reg_midatl+ reg_encen + reg_wncen + reg_satl + reg_escen + reg_wscen + reg_mount + reg_pacif + t2, weights = timepwt48, clusters = statefip, data = workfile_china, se_type = "stata") 

table3_2_5 <- lm_robust(d_tradeusch_pw ~ d_tradeotch_pw_lag + l_shind_manuf_cbp + l_sh_routine33 + l_task_outsource + reg_midatl+ reg_encen + reg_wncen + reg_satl + reg_escen + reg_wscen + reg_mount + reg_pacif + t2, weights = timepwt48, clusters = statefip, data = workfile_china, se_type = "stata") 

table3_2_6 <- lm_robust(d_tradeusch_pw ~ d_tradeotch_pw_lag + l_shind_manuf_cbp + l_sh_popedu_c + l_sh_popfborn + l_sh_empl_f + l_sh_routine33 + l_task_outsource + reg_midatl+ reg_encen + reg_wncen + reg_satl + reg_escen + reg_wscen + reg_mount + reg_pacif + t2, weights = timepwt48, clusters = statefip, data = workfile_china, se_type = "stata") 

summary(table3_2_1)
summary(table3_2_2)
summary(table3_2_3)
summary(table3_2_4)
summary(table3_2_5)
summary(table3_2_6)
```

standard error が論文のtable3 IIの内容と異なっているが、replication packageのstata code を実行したところ、上記の結果と一致したため、論文に表記されているstandard errorが誤っていると考えられる。
